version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flores_backend
    ports:
      - "5281:5281"
    environment:
      - ASPNETCORE_URLS=http://+:5281
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=FloresDb;User Id=sa;Password=Welkom#1;TrustServerCertificate=True;

  frontend:
    build: ./frontend
    container_name: flores_frontend
    ports:
      - "3000:3000"
    environment:
     - NEXT_PUBLIC_API_URL=http://backend:5281
    depends_on:
      - backend
